name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - "*"

jobs:
  build:
    # use freecad-x64 runner
    runs-on:
      group: freecad-x64

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and Push for AMD64
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/amd64
      #     push: true
      #     tags: ghcr.io/uptoolapp/freecad:amd64
        
      - name: Build and Push for ARM64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/uptoolapp/freecad:arm64
        
      - name: Merge Multi-Arch Image
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/uptoolapp/freecad:latest \
            ghcr.io/uptoolapp/freecad:amd64 \
            ghcr.io/uptoolapp/freecad:arm64
