on: push
jobs:
  build-release:
    strategy:
      matrix:
          include:
            - { arch: 'arm64' }
            - { arch: 'amd64' }
    runs-on: freecad-${{ matrix.arch }}
    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Build
        run: docker build --target builder --tag builder .

      - name: Test
        run: docker build --target tester --tag tester .
        
      - name: Prepare artifacts
        run: |
          mkdir /tmp/release_artifacts
          docker run --rm builder cat /tmp/packaging/freecad-uptool.deb >/tmp/release_artifacts/freecad-uptool_${{ matrix.arch }}.deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release_artifacts-${{ matrix.arch }}
          path: /tmp/release_artifacts/*
          compression-level: 0 # already compressed

  release:
    needs: [build-release]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: release_artifacts-*
          path: /tmp/release_artifacts
          merge-multiple: true

      - name: List artifacts
        run: |
          ls -lh /tmp/release_artifacts

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/release_artifacts/*